apiVersion: v1
kind: Namespace
metadata:
  name: techtalk
---
apiVersion: v1
kind: Service
metadata:
  name: kubetalk
  namespace: techtalk
  labels:
    app: kubetalk
spec:
  selector:
    app: kubetalk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: techtalk
  name: kubetalk
  labels:
    app: kubetalk
spec:
  selector:
    matchLabels:
      app: kubetalk
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetalk
    spec:
      containers:
      - name: kubetalk
        image: cmillani/node-sample
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          name: kubetalk
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kubetalk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubetalk
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50